-- Seed data for RegretWall
-- Run this in Supabase SQL editor after creating the schema

insert into regrets (text, topic, age_range, created_at) values
  ('I wish I had told my dad I loved him before he passed. I always assumed there would be more time.', 'family', '36-50', now() - interval '2 hours'),
  ('I should have taken that job in Tokyo. I was scared of being alone in a foreign country. Now I''m alone here anyway.', 'career', '26-35', now() - interval '3 hours'),
  ('I spent my 20s trying to be impressive instead of being honest. I don''t even know who I actually am.', 'fear', '26-35', now() - interval '5 hours'),
  ('I wish I had saved money in my twenties instead of trying to look rich.', 'money', '36-50', now() - interval '6 hours'),
  ('I should have kissed her that night on the rooftop. She moved to another city the next week.', 'love', '18-25', now() - interval '8 hours'),
  ('I regret not going to therapy sooner. I wasted years being angry at everyone when I was really angry at myself.', 'health', '26-35', now() - interval '10 hours'),
  ('I wish I had learned to cook when my grandmother was still alive. She offered to teach me every summer.', 'family', '26-35', now() - interval '12 hours'),
  ('I should have studied what I loved instead of what seemed safe. Now I have a stable job I hate.', 'career', '26-35', now() - interval '14 hours'),
  ('I regret being so hard on my kids when they were young. I was repeating my parents'' mistakes.', 'family', '50+', now() - interval '16 hours'),
  ('I wish I had traveled before settling down. Now I look at maps and wonder.', 'fear', '36-50', now() - interval '18 hours'),
  ('I should have told the truth that day. The lie was easier but it cost me the only person who really knew me.', 'love', '26-35', now() - interval '20 hours'),
  ('I regret not standing up for myself at work for years. I kept quiet and they kept taking.', 'career', '36-50', now() - interval '22 hours'),
  ('I wish I had taken my health seriously in my 30s. Your body keeps a tab.', 'health', '50+', now() - interval '1 day'),
  ('I should have called more. Texting isn''t the same. Now there''s no one to call.', 'family', '36-50', now() - interval '1 day 2 hours'),
  ('I regret every Sunday I spent hungover instead of doing something that mattered.', null, '26-35', now() - interval '1 day 4 hours'),
  ('I wish I had the courage to leave sooner. I knew it was over for two years before I finally walked away.', 'love', '26-35', now() - interval '1 day 6 hours'),
  ('I should have listened when people told me to slow down. Burnout doesn''t announce itself.', 'health', '26-35', now() - interval '1 day 8 hours'),
  ('I regret not learning another language when my brain could still absorb things effortlessly.', null, '36-50', now() - interval '1 day 10 hours'),
  ('I wish I had been kinder to my younger brother. He looked up to me and I treated him like a nuisance.', 'family', '26-35', now() - interval '1 day 12 hours'),
  ('I should have started writing years ago. All those stories died inside me because I was afraid they weren''t good enough.', 'fear', '36-50', now() - interval '1 day 14 hours'),
  ('I regret choosing comfort over growth every single time. Comfort is a slow poison.', 'fear', '26-35', now() - interval '1 day 16 hours'),
  ('I wish I hadn''t ghosted her. She deserved an explanation at the very least.', 'love', '18-25', now() - interval '1 day 18 hours'),
  ('I should have asked for help instead of pretending everything was fine. Pride is expensive.', 'health', '26-35', now() - interval '1 day 20 hours'),
  ('I regret not spending more time with my dog. He was always happy to see me and I was always busy.', null, '26-35', now() - interval '2 days'),
  ('I wish I had said no more often. I spent decades being agreeable and lost myself in the process.', 'fear', '50+', now() - interval '2 days 3 hours'),
  ('I should have invested in experiences, not things. My storage unit is full. My memories are sparse.', 'money', '36-50', now() - interval '2 days 6 hours'),
  ('I regret not being there when my mom needed me. I was chasing a promotion that didn''t even last.', 'family', '36-50', now() - interval '2 days 9 hours'),
  ('I wish I had danced more and worried less about looking stupid.', null, '26-35', now() - interval '2 days 12 hours'),
  ('I should have forgiven him while he was still alive. Now I carry the weight for both of us.', 'family', '50+', now() - interval '2 days 15 hours'),
  ('I regret not taking that gap year. Everyone said it was irresponsible. Now I''ll never be 18 again.', 'fear', '18-25', now() - interval '2 days 18 hours');
